M48
; DRILL file {KiCad 9.0.7+1} date 2026-04-12T13:59:44+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-12T13:59:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X256.22Y-144.61
X256.22Y-150.39
T2
X215.5Y-154.957
X218.374Y-150.647
X219.81Y-152.083
M30
